try{

    console.log(c+d);
} catch(error){


    console.log("Hello");

}

console.log('This line now runs');
